config/routes.rb
FeatureGirl::Application.routes.draw do
  resources :tags

  resources :features
  resources :scenarios

  match 'network' => 'scenarios#network', :as => 'network'
  match 'scenarios/tag/:id/:tag', :to => 'scenarios#tag'
  match 'scenarios/untag/:id/:tag/', :to => 'scenarios#untag'
  
  root :to => 'scenarios#network'
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :feature

  acts_as_taggable_on :tags

  validates_presence_of :title, :steps
end

app/models/scenarios.rb
class Scenario < ActiveRecord::Base
  belongs_to :feature
  acts_as_taggable_on :tags
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  # GET /scenarios
  # GET /scenarios.xml
  def index
    @scenarios = Scenario.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scenarios }
    end
  end

  # GET /scenarios/1
  # GET /scenarios/1.xml
  def show
    @scenario = Scenario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scenario }
    end
  end

  # GET /scenarios/new
  # GET /scenarios/new.xml
  def new
    @scenario = Scenario.new
    @features = Feature.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scenario }
    end
  end

  # GET /scenarios/1/edit
  def edit
    @scenario = Scenario.find(params[:id])
    @features = Feature.all
  end

  # POST /scenarios
  # POST /scenarios.xml
  def create
    @scenario = Scenario.new(params[:scenario])

#    respond_to do |format|
      if @scenario.save
        redirect_to network_path
#        format.html { redirect_to(@scenario, :notice => 'Scenario was successfully created.') }
#        format.xml  { render :xml => @scenario, :status => :created, :location => @scenario }
      else
        redirect_to network_path
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @scenario.errors, :status => :unprocessable_entity }
#      end
    end
  end

  # PUT /scenarios/1
  # PUT /scenarios/1.xml
  def update
    @scenario = Scenario.find(params[:id])

    respond_to do |format|
      if @scenario.update_attributes(params[:scenario])
        format.html { redirect_to(@scenario, :notice => 'Scenario was successfully updated.') }
        format.xml  { head :ok }
        format.json { render :json => { :success => true } }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scenario.errors, :status => :unprocessable_entity }
        format.json { render :json => { :success => false } }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.xml
  def destroy
    @scenario = Scenario.find(params[:id])
    @scenario.destroy

    respond_to do |format|
      format.html { redirect_to(network_url) }
      format.xml  { head :ok }
    end
  end

  # GET /network
  # get a jquery-draggable network of scenarios and tags
  def network
    @scenario = Scenario.new
    @scenarios = Scenario.all(:include => :tags)
    @tags = @scenarios.collect{|s| s.tags}.flatten.uniq
  end

  # save tag to scenario by id
  # not sure that this is the most succint way to do this
  def tag
    @scenario = Scenario.find(params[:id]);
    tl = @scenario.tag_list
    tl << Tag.find_by_id(params[:tag]).name;
    @scenario.tag_list = tl
    respond_to do |format|
      if @scenario.update_attributes(@scenario)
        format.json { render :json => { :success => true } }
      else
        format.json { render :json => { :success => false} }
      end
    end
  end

  def untag
    tagging = Tagging.find_by_taggable_id_and_tag_id(params[:id], params[:tag])
    respond_to do |format|
      if tagging.destroy
        format.json { render :json => { :success => true } }
      else
        format.json { render :json => { :success => false} }
      end
    end
  end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper

  # returns a color based on the total number of objects that need a color and the index of the current object
  # starts with red, ends with purple
  def get_unique_color(total, index)
    per = index.to_f / total
    if per >= 0 and per <= 0.2
      #start with red
      #raise green
      red = 255
      green = (per/0.2) * 255
      blue = 0
    elsif per > 0.2 and per <= 0.4
      #lower red
      red = 255 - (((per - 0.2)/0.2) * 255)
      green = 255
      blue = 0
    elsif per > 0.4 and per <= 0.6
      #raise blue
      red = 0
      green = 255
      blue = ((per - 0.4)/0.2) * 255
    elsif per > 0.6 and per <= 0.8
      #lower green
      red = 0
      green = 255 - (((per - 0.6)/0.2) * 255)
      blue = 255
    elsif per > 0.8 and per <= 1.0
      #raise red
      red = ((per - 0.8)/0.2) * 255
      green = 0
      blue = 255
    elsif per > 1 or per < 0
      #error condition
      red = 255
      green = 255
      blue = 255
    end
    hex = to_hex(red) + to_hex(green) + to_hex(blue)
    return "##{hex}"
  end

  # converts float or int to hex and zero pads if it is a single hex digit
  def to_hex(input)
    input = input.to_i.to_s(16)
    if input.length == 1
      return '0' + input
    end
    return input
  end
end

app/views/scenarios/_form.html.haml
= form_for @scenario do |f|
  -if @scenario.errors.any?
    #error_explanation
      %h2= "#{pluralize(@scenario.errors.count, "error")} prohibited this scenario from being saved:"
      %ul
        - @scenario.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :steps
    = f.text_area :steps
  .field
    = f.label :tag_list
    = f.text_area :tag_list
  .actions
    = f.submit 'Save'

app/views/scenarios/edit.html.haml
%h1 Editing scenario

= render 'form'

= link_to 'Show', @scenario
\|
= link_to 'Back', scenarios_path

app/views/scenarios/index.html.haml
%h1 Listing scenarios

%table
  %tr
    %th Title
    %th Steps
    %th Tags
    %th Feature
    %th
    %th
    %th

  - @scenarios.each do |scenario|
    %tr
      %td= scenario.title
      %td= scenario.steps.gsub('\n', '<br />').html_safe
      %td= scenario.tag_list
      %td= scenario.feature.title if !scenario.feature.nil?
      %td= link_to 'Show', scenario
      %td= link_to 'Edit', edit_scenario_path(scenario)
      %td= button_to 'Destroy', scenario_path(scenario),  :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Scenario', new_scenario_path

app/views/scenarios/network.html.haml
= stylesheet_link_tag 'network'

<canvas id="canvas" width="3600px" height="2400px"></canvas>
.links
  = link_to "FEATURE-GIRL", '/', :class => 'feature-girl'
  = link_to 'New Test', "#new_scenario", :id => "inline", :class => "new_scenario_form"
  = '::'
  = link_to 'Tests', scenarios_path
  = '::'
  = link_to 'Tags', tags_path
  .plain
    <a href='#' style='display:none' id='randomize'>Randomly Arrange Items</a>



.info_bar
  .scenario_info
    .top_bar
      .title_info
        Title:
        %span.title
      .tags_info
        Tags:
        %span.tags
    .steps
      Click on a Test or FeatureTag to view details!
  .tag_info
    .top_bar
      .title_info
        Title:
        %span.title
    .description
    .scenarios
      Scenarios: 
      %span.scenarios

.new_scenario_bar
  .field
    %div.text
      Create New Scenario
    %div.new_scenario_bar_hide
      Hide
  = render "form" 

.scenarios
  - @scenarios.each do |scenario|
    .scenario_object{ :id => "scenario_#{scenario.id}", :style => "left: #{scenario.left}px; top: #{scenario.top}px; position: absolute;" }
      .modify_bar
        .delete
          = link_to image_tag('/images/delete.gif', :width => '10px', :height => '10px'), scenario_path(scenario), :method => :delete
        .edit
          = link_to image_tag('/images/edit.png', :width => '15px', :height => '10px'), edit_scenario_path(scenario)
      .scenario_portal{ :id => "scenario_portal_#{scenario.id}" }
        = image_tag('/images/orange_portal.png')
        .scenario_portal_tag{ :id => "scenario_portal_tag_#{scenario.id}", :style => 'display:none' }
      .info
        = scenario.title
             
      .hidden_info
        .title
          = scenario.title
        .steps{ :id => "scenario_#{scenario.id}_steps", :style => "display:none;" }
          - (h scenario.steps).gsub(/(Given|When|Then|And)/, '<font color=#20B87E>\1</font>').gsub(/"([^"]*)"/, '<font color=blue>"\1"</font>').split('\n').each do |step|
            .step{ :class => cycle('', 'cycle') }= raw step
        .tags
          - scenario.tags.each do |tag|
            = link_to tag.name, tag_path(tag)

.tags
  - @tags.each_with_index do |tag, index|
    .tag_object{ :id => "tag_#{tag.id}", :style => "left: #{tag.left}px; top: #{tag.top}px; background-color: #{get_unique_color(@tags.count,index)}; position:absolute;" }
      .tag_portal{ :id => "tag_portal_#{tag.id}" }
        = image_tag('/images/blue_portal.png')
      .info
        = tag.name
      .hidden_info
        .title= tag.name
        /.description= tag.description
        /.scenarios= tag.scenarios.collect{|s|s.name}.join(', ')



.inline_content{ :style => 'display:none' }
  .new_scenario_form
    = render :partial => 'scenarios/form'

 
-#%ul.features
  %li= link_to 'Show', scenario
  %li= link_to 'Edit', edit_scenario_path(scenario)
  %li= button_to 'Destroy', scenario_path(scenario),  :confirm => 'Are you sure?', :method => :delete

:javascript 
  var s = 0;
  var s2 = 0;
  function printtime(){ var d = new Date();
  s2 = d.getTime() * 1000 + d.getMilliseconds();
  //console.log(s2-s);
  s = s2;
  }



  // Globals
  var canvas = $('#canvas')[0]
  var ctx = canvas.getContext('2d');
  var connections = [ #{@scenarios.collect { |s| s.tags.collect { |t| "{ from: $('#scenario_" + s.id.to_s + "'), to: $('#tag_" + t.id.to_s + "') }" } }.join(', ') } ];

  function connect(scen, tag) { 
    ctx.strokeStyle = tag.css('border-left-color');
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(scen.offset().left + scen.width()/2, scen.offset().top + scen.height()/2);
    ctx.lineTo(tag.offset().left + tag.width()/2, tag.offset().top + tag.height()/2);
    ctx.strokeStyle = tag.css('background-color');
    ctx.stroke();
  }

  function update_canvas() {
    canvas.width = canvas.width;
    //#{@scenarios.collect { |scenario| scenario.tags.collect { |tag| "connect($('#scenario_" + scenario.id.to_s + "'), $('#tag_" + tag.id.to_s + "'));" } } }
    for (var i=0; i<connections.length; i++) { 
      if (typeof(connections[i]) != 'undefined' && connections[i].from.size() > 0 && connections[i].to.size() > 0) {
        connect(connections[i].from, connections[i].to);
      }
    }
  }

  //sets z index high when dragging, and below a click when done dragging
  $('.scenario_object, .tag_object').draggable({
    start: function(e,ui) { set_info_bar_content(this); $(this).css('z-index', 1000); },
    drag: function(e,ui) { update_canvas(); },
    stop: function(e, ui) { 
      save_position(ui.helper);
      $(this).css('z-index', 499);
   }
  });

  update_canvas();


  function randomize() { 
    $('.scenario_object, .tag_object').each(function() { 
      $(this).css('left', Math.random()*1024); $(this).css('top', Math.random()*768); 
      save_position($(this));
    });
    update_canvas();
    return false;
  }
  
  function save_position(element) {
    var url = '', post_data = '', type = '', id = ''

    // determine which type of element we are dragging
    type = element.attr('class').match(/([^ ]+)_object/)[1];

    id = element.attr('id').replace(type+'_', '');
      
    url = '/' + type + 's/' + id + '.json';
    post_data = "_method=put" +
                "&" + type + "[left]=" + element.offset().left +
                "&" + type + "[top]=" + element.offset().top;

    $.post(url, post_data, function(d,t){
      update_canvas();
    });
  }

  $('#randomize').click(randomize);


  // function for calculating the distance of a point from a line with an equation of y = m*x + b
  function distance_of_point_from_line(x, y, m, b) {
    // find the m and b for the line perpendicular that contains the mouse pointer
    var m2 = -1/m;
    var b2 = y - m2 * x;

    // find intersection of the real line and the perpendicular line
    var yi = (b*m2 - b2*m)/(m2-m);
    var xi = (y-b)/m;
    
    // find the distance from the intersection and the mouse pointer
    return Math.sqrt(Math.pow( (xi-x), 2 ) + Math.pow( (yi-y), 2 ) );
  }

  function colinear(start, end, point, error)  {
    // find m and b of the line for y=mx+b
    var m = (start.y - end.y)/(start.x - end.x);
    var b = end.y - m * end.x;
    
    var distance = distance_of_point_from_line(point.x, point.y, m, b);
    
    //get crossproduct
    val =  ((end.x - start.x) * (point.y - start.y)) - ((point.x - start.x) * (end.y - start.y))
    if(Math.abs(val) <= error)  {
      return true;
    }
    if (distance < 10) { return true; }
    return false;
  }

  function inside_bounding_box(start, end, point, error)  {
    //if abs is slow, negate end and add the or
    if((
        (start.x + error >= point.x && point.x >= end.x - error) 
        || (end.x + error >= point.x && point.x >= start.x - error)
      ) && (
        (start.y + error >= point.y && point.y >= end.y - error) 
        || (end.y + error >= point.y && point.y >= start.y - error)
      ))  {
      return true;
    }
    return false;
  }

  $('.scenario_portal').hide();

  $('#canvas').click(function(e)  {
    window.r = e;
    click = { x: e.layerX, y: e.layerY };

    //deactivate the Portal Themed tagging system
    $('.scenario_portal').hide();

    // delete the lines that are within 3 pixels of the cursor
    $.each(connections, function(index, value)  {
      if (typeof(value) == 'undefined') { return; }
      f = value.from;
      t = value.to;
      from = { x: f.offset().left + f.width()/2, y: f.offset().top + f.height()/2 };
      to = { x: t.offset().left + t.width()/2, y: t.offset().top + t.height()/2 };
      allowable_error = 3; //3 pixels
      if( inside_bounding_box(from, to, click, allowable_error))  {
        if(colinear(from, to, click, allowable_error))  {
          scen_id = value.from.attr('id').replace('scenario_', '');
          tag_id = value.to.attr('id').replace('tag_', '');
          
          $.post('/scenarios/untag/' + scen_id + '/' + tag_id + '.json', '_method=put', function(d,t) {
            connections.splice(index,1);
            update_canvas();
          });
        }
      }
    });
  });

  function set_info_bar_content(item) {
    item = $(item);
    if (item.hasClass('scenario_object')) {
      $('.tag_info').hide();
      $('.scenario_info').show();
      $('.scenario_info .title').html(item.find('.title').html());
      $('.scenario_info .steps').html(item.find('.steps').html());
      $('.scenario_info .tags').html(item.find('.tags').html());
    } else if (item.hasClass('tag_object')) {
      $('.scenario_info').hide();
      $('.tag_info').show();
      $('.tag_info .title').html(item.find('.title'));
      //$('.tag_info .description').html(item.find('.description'));
      //$('.tag_info .scenarios').html(item.find('.scenarios'));
    }
  }

  //sets to high z-index but lower than dragging index
  $('.scenario_object, .tag_object').click(function()  {
    $(this).css('z-index', 500);
    set_info_bar_content(this);
  });

 
  //hide the link, show the steps
  $('.steps_link').click(function(){
    steps_div = $(this).attr('id').replace('_link', '');
    $(this).css('display', 'none');
    $('#' + steps_div).css('display', 'block');
    update_canvas();
  });

  //click on the tag portal to active the scenario portal
  $('.tag_portal').click(function(){
    $('.scenario_portal').show();
    $('.scenario_portal_tag').html($(this).attr('id'));
  });

  //click on the scenario portal to make the connection
  $('.scenario_portal').click(function(){
    //get div information
    scen_div_id = $(this).attr('id');
    tag_div_id = $('#' + scen_div_id.replace('scenario_portal_', 'scenario_portal_tag_')).html();
    //alert("now you are thinking with portals: " + scen_div_id  + " and " + tag_div_id);
    scen_id = scen_div_id.replace('scenario_portal_', '');
    tag_id = tag_div_id.replace('tag_portal_', '');
      
    //setup post request
    url = '/scenarios/tag/' + scen_id + '/' + tag_id + '.json'
    post_data = "_method=put";

    $.post(url, post_data, function(d,t){
      //update the connections
      //probably another post call
      connections.push({ from: $("#scenario_" + scen_id), to: $("#tag_" + tag_id) });
      update_canvas();
    });
    $('.scenario_portal_tag').html('none');
    $('.scenario_portal').css('display', 'none');

  });
  
  $('delete_scenario_link').click(function() {
    $.post(this.href, '_method=delete', function(d,t) {
      window.location.reload(true);
    });
    this.href="#";
    return false;
  });







  // canvas drawing helpers
  function drawRoundedRect(x, y, w, h) {
    var x2 = x+w;
    var y2 = y+h;
    ctx.beginPath();
    ctx.moveTo(x+c, y);
    ctx.lineTo(x2-c, y);
    ctx.quadraticCurveTo(x2,y, x2,y+c);
    ctx.lineTo(x2, y2-c);
    ctx.quadraticCurveTo(x2,y2, x2-c,y2);
    ctx.lineTo(x+c, y2);
    ctx.quadraticCurveTo(x,y2, x,y2-c);
    ctx.lineTo(x, y+c);
    ctx.quadraticCurveTo(x,y, x+c,y);
    ctx.stroke();
  }

app/views/scenarios/new.html.haml
%h1 New scenario

= render 'form'

= link_to 'Back', scenarios_path

app/views/scenarios/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @scenario.title
%p
  %b Steps:
  = @scenario.steps
%p
  %b Tags
  - @scenario.tag_list.each do |tag|
    = link_to tag, '#'
    ,

= link_to 'Edit', edit_scenario_path(@scenario)
\|
= link_to 'Back', scenarios_path