config/routes.rb
FeatureGirl::Application.routes.draw do
  resources :tags

  resources :features
  resources :scenarios

  match 'network' => 'scenarios#network', :as => 'network'
  match 'scenarios/tag/:id/:tag', :to => 'scenarios#tag'
  match 'scenarios/untag/:id/:tag/', :to => 'scenarios#untag'
  
  root :to => 'scenarios#network'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeatureGirl</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery-ui.min.js' %>
  <%= javascript_include_tag 'jquery.fancy_box/load_fancybox.js' %>
  <%= javascript_include_tag 'jquery.fancy_box/jquery.easing-1.3.pack.js' %>
  <%= javascript_include_tag 'jquery.fancy_box/jquery.fancybox-1.3.1.pack.js' %>
  <%= javascript_include_tag 'jquery.fancy_box/jquery.mousewheel-3.0.2.pack.js' %>
  <%= javascript_include_tag 'jquery.fancy_box/jquery.fancybox-1.3.1.js' %>
  <%= stylesheet_link_tag 'jquery.fancybox.css' %>
  <%= csrf_meta_tag %>

  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21436180-1']);
  _gaq.push(['_trackPageview']);
  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
</head>
<body>

  <%= link_to "Feature-Girl Main Page", network_path unless request.url =~ /\/network$/ or request.url =~ /\/$/ %>

<%= yield %>

</body>
</html>